import { Raleway } from 'next/font/google';
import '../styles/globals.scss';
import Provider from './provider';
import '../styles/styles.scss';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { locale } }) {
	return (
		<html lang={locale}>
			<body className={raleway.className}>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
